siteName: assemble with YAML demo
footerLinks:
  - title: assemble
    url: http://assemble.io/
  - title: DeNA
    url: http://dena.com/jp/
  - title: recruit staffing
    url: http://www.r-staffing.co.jp/
